export const metadata = {
  title: "SBU AI Professor Search",
  description: "Generated by create next app",
};
import "./globals.css"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
