export const metadata = {
  title: "SBU AI Professor Search",
  description: "Generated by create next app",
};
import "./globals.css"
import { Toaster } from 'react-hot-toast'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Toaster position="top-center"></Toaster>{children}</body>
    </html>
  );
}
